- hosts: worker-1
  become: yes
  tasks: 
  - apt: name=firewalld state=present
  - service: name=firewalld state=started
  - firewalld:
      port: 80/tcp
      zone: public
      state: enabled
      permanent: yes
      immediate: yes
  - service: name=firewalld state=reloaded