- hosts: web1
  become: yes
  tasks:
  - blockinfile:
      block: | 
        Welcome to KodeKloud!
        This is Ansible Lab.
      path: /var/www/html/index.html
      owner: apache
      group: apache   
      insertbefore: BOF
~                       